import { Document, Page, StyleSheet, View } from "@formepdf/react";

import { DataTable } from
    "@/components/pdf/data-table/data-table";
import { PdfGraph } from "@/components/pdf/graph/graph";
import type { GraphSeries } from
    "@/components/pdf/graph/graph.types";
import { KeyValue } from "@/components/pdf/key-value/key-value";
import { PdfList } from "@/components/pdf/list/list";
import { PageFooter } from
    "@/components/pdf/page-footer/page-footer";
import { PageHeader } from
    "@/components/pdf/page-header/page-header";
import { Section } from "@/components/pdf/section/section";
import { Text } from "@/components/pdf/text/text";
import { PdfcnThemeProvider } from
    "@/components/pdf/theme-provider";
import { professionalTheme } from
    "@/lib/pdf-themes/professional";
import type { DashboardData } from "@/modules/dashboard/types";
import type {
    ReportDateRange,
    SalesReport,
} from "@/modules/reports/types";

export type OverviewPdfData = {
    businessName: string;
    currencyCode: string;
    dashboard: DashboardData;
    dateRange: ReportDateRange;
    generatedAt: string;
    sales: SalesReport;
};

type PdfTableRow = Record<string, unknown>;

const styles = StyleSheet.create({
    agingChart: {
        borderColor: "#e4e4e7",
        borderRadius: 4,
        borderStyle: "solid",
        borderWidth: 1,
        padding: 10,
    },
    footerGap: {
        marginTop: 16,
    },
    metricCard: {
        backgroundColor: "#f4f4f5",
        flex: 1,
        padding: 10,
    },
    metricLabel: {
        letterSpacing: 0.5,
        marginBottom: 4,
        textTransform: "uppercase",
    },
    metricRow: {
        flexDirection: "row",
        gap: 8,
    },
    page: {
        backgroundColor: "#ffffff",
    },
    riskGrid: {
        flexDirection: "row",
        gap: 18,
    },
    riskColumn: {
        flex: 1,
    },
    sectionTitle: {
        letterSpacing: 0.5,
        marginBottom: 8,
        textTransform: "uppercase",
    },
});

const percent = new Intl.NumberFormat("en-PH", {
    maximumFractionDigits: 1,
});

const quantity = new Intl.NumberFormat("en-PH", {
    maximumFractionDigits: 1,
});

function formatPdfCurrency(value: number, currencyCode: string) {
    try {
        return new Intl.NumberFormat("en-PH", {
            currency: currencyCode,
            maximumFractionDigits: 0,
            style: "currency",
        }).format(value);
    } catch {
        return `${currencyCode} ${quantity.format(value)}`;
    }
}

function formatChartDate(value: string) {
    const date = new Date(`${value}T00:00:00Z`);

    if (Number.isNaN(date.getTime())) {
        return value;
    }

    return new Intl.DateTimeFormat("en", {
        day: "numeric",
        month: "short",
        timeZone: "UTC",
    }).format(date);
}

function MetricCard({
    label,
    value,
}: {
    label: string;
    value: string;
}) {
    return (
        <View style={styles.metricCard}>
            <Text
                color="mutedForeground"
                noMargin
                style={styles.metricLabel}
                variant="xs"
            >
                {label}
            </Text>
            <Text noMargin variant="lg" weight="bold">
                {value}
            </Text>
        </View>
    );
}

function DocumentFooter() {
    return (
        <PageFooter
            centerText="Generated by StockWise"
            leftText="Business overview"
            pagePadding={48}
            rightText="Confidential"
            sticky
            variant="three-column"
        />
    );
}

export function StockWiseOverviewPdfDocument({
    data,
}: {
    data: OverviewPdfData;
}) {
    const { dashboard, sales } = data;
    const { inventory_efficiency: efficiency } = dashboard;
    const risk = dashboard.inventory_risk;
    const pendingReorders = risk.pending_reorder_recommendations;
    const deliveriesToday = risk.expected_deliveries_today;
    const salesAtRisk = risk.estimated_sales_at_risk;
    const revenue = sales.summary.total_revenue;
    const profit = sales.summary.total_profit;
    const margin = revenue > 0 ? (profit / revenue) * 100 : 0;
    const period = `${data.dateRange.startDate} to ` +
        data.dateRange.endDate;
    const chartPoints = sales.by_day.length > 0
        ? sales.by_day
        : [{
            date: data.dateRange.startDate,
            profit: 0,
            revenue: 0,
            sales_count: 0,
        }];
    const performance: GraphSeries[] = [
        {
            color: "#2563eb",
            data: chartPoints.map((point) => ({
                label: formatChartDate(point.date),
                value: point.revenue,
            })),
            name: "Revenue",
        },
        {
            color: "#93c5fd",
            data: chartPoints.map((point) => ({
                label: formatChartDate(point.date),
                value: point.profit,
            })),
            name: "Gross profit",
        },
    ];
    const aging = efficiency.aging_buckets.map((bucket) => ({
        color: {
            active: "#2563eb",
            at_risk: "#93c5fd",
            dead_stock: "#dbeafe",
            slowing: "#60a5fa",
        }[bucket.key],
        label: {
            active: "Active",
            at_risk: "Very slow",
            dead_stock: "Dead stock",
            slowing: "Slowing",
        }[bucket.key],
        value: bucket.inventory_value,
    }));
    const actions = efficiency.actions.slice(0, 5);
    const actionItems = actions.length > 0
        ? actions.map((action) => ({
            text: `${action.product_name}: ${action.suggested_action}`,
        }))
        : [{ text: "No inventory actions need attention." }];
    const topProducts: PdfTableRow[] = sales.top_products
        .slice(0, 10)
        .map((product) => ({
            product: product.product_name,
            profit: formatPdfCurrency(
                product.profit,
                data.currencyCode,
            ),
            quantity: quantity.format(product.quantity_sold),
            revenue: formatPdfCurrency(
                product.revenue,
                data.currencyCode,
            ),
            sku: product.sku || "-",
        }));

    return (
        <PdfcnThemeProvider theme={professionalTheme}>
            <Document title={`StockWise overview - ${period}`}>
                <Page
                    margin={{
                        bottom: 48,
                        left: 48,
                        right: 48,
                        top: 48,
                    }}
                    size="A4"
                >
                    <DocumentFooter />
                    <View style={styles.page}>
                        <PageHeader
                            marginBottom={14}
                            rightSubText={`Generated ${data.generatedAt}`}
                            rightText={period}
                            subtitle={data.businessName}
                            title="Business overview"
                            variant="two-column"
                        />

                        <Section noWrap spacing="none">
                            <Text
                                color="mutedForeground"
                                noMargin
                                style={styles.sectionTitle}
                                variant="xs"
                            >
                                Business health
                            </Text>
                            <View style={styles.metricRow}>
                                <MetricCard
                                    label="Revenue"
                                    value={formatPdfCurrency(
                                        revenue,
                                        data.currencyCode,
                                    )}
                                />
                                <MetricCard
                                    label="Gross profit"
                                    value={formatPdfCurrency(
                                        profit,
                                        data.currencyCode,
                                    )}
                                />
                                <MetricCard
                                    label="Margin"
                                    value={`${percent.format(margin)}%`}
                                />
                                <MetricCard
                                    label="Inventory"
                                    value={formatPdfCurrency(
                                        dashboard.kpis.inventory_value,
                                        data.currencyCode,
                                    )}
                                />
                            </View>
                            <Text
                                color="mutedForeground"
                                noMargin
                                style={{ marginTop: 6 }}
                                variant="xs"
                            >
                                Gross profit is before operating expenses,
                                salaries, rent, taxes, and other costs.
                            </Text>
                        </Section>

                        <Section spacing="sm">
                            <Text
                                color="mutedForeground"
                                noMargin
                                style={styles.sectionTitle}
                                variant="xs"
                            >
                                Performance
                            </Text>
                            <PdfGraph
                                colors={["#2563eb", "#93c5fd"]}
                                data={performance}
                                fullWidth
                                height={215}
                                legend="bottom"
                                showDots={false}
                                smooth
                                subtitle="Revenue and gross profit"
                                title="Sales performance"
                                variant="line"
                            />
                        </Section>

                        <Section
                            padding="md"
                            spacing="none"
                            variant="card"
                        >
                            <Text
                                color="mutedForeground"
                                noMargin
                                style={styles.sectionTitle}
                                variant="xs"
                            >
                                Needs attention
                            </Text>
                            <View style={styles.riskGrid}>
                                <View style={styles.riskColumn}>
                                    <KeyValue
                                        divided
                                        items={[
                                            {
                                                key: "Out of stock",
                                                value: String(
                                                    risk.out_of_stock_skus,
                                                ),
                                            },
                                            {
                                                key: "Low stock",
                                                value: String(
                                                    risk.low_stock_skus,
                                                ),
                                            },
                                            {
                                                key: "Below reorder point",
                                                value: String(
                                                    risk.below_reorder_point,
                                                ),
                                            },
                                            {
                                                key: "Under stock target",
                                                value: String(
                                                    risk.below_days_of_stock,
                                                ),
                                            },
                                        ]}
                                        size="sm"
                                    />
                                </View>
                                <View style={styles.riskColumn}>
                                    <KeyValue
                                        divided
                                        items={[
                                            {
                                                key: "Pending reorders",
                                                value: String(pendingReorders),
                                            },
                                            {
                                                key: "Deliveries today",
                                                value: String(deliveriesToday),
                                            },
                                            {
                                                key: "Late purchase orders",
                                                value: String(
                                                    risk.late_purchase_orders,
                                                ),
                                            },
                                            {
                                                key: "Sales at risk",
                                                value: formatPdfCurrency(
                                                    salesAtRisk,
                                                    data.currencyCode,
                                                ),
                                            },
                                        ]}
                                        size="sm"
                                    />
                                </View>
                            </View>
                        </Section>
                    </View>
                </Page>

                <Page
                    margin={{
                        bottom: 48,
                        left: 48,
                        right: 48,
                        top: 48,
                    }}
                    size="A4"
                >
                    <DocumentFooter />
                    <View style={styles.page}>
                        <PageHeader
                            marginBottom={14}
                            rightText={period}
                            subtitle="Inventory exposure and actions"
                            title={data.businessName}
                            variant="two-column"
                        />

                        <Section
                            padding="md"
                            spacing="none"
                            variant="card"
                        >
                            <Text
                                color="mutedForeground"
                                noMargin
                                style={styles.sectionTitle}
                                variant="xs"
                            >
                                Capital at risk
                            </Text>
                            <KeyValue
                                divided
                                items={[
                                    {
                                        key: "Dead-stock value",
                                        value: formatPdfCurrency(
                                            efficiency.dead_stock_value,
                                            data.currencyCode,
                                        ),
                                    },
                                    {
                                        key: "Share of inventory value",
                                        value: `${percent.format(
                                            efficiency
                                                .dead_stock_percentage,
                                        )}%`,
                                    },
                                    {
                                        key: "Capital tied up",
                                        value: formatPdfCurrency(
                                            efficiency.capital_tied_up,
                                            data.currencyCode,
                                        ),
                                    },
                                ]}
                                size="sm"
                            />
                        </Section>

                        <Section spacing="sm">
                            <Text
                                color="mutedForeground"
                                noMargin
                                style={styles.sectionTitle}
                                variant="xs"
                            >
                                Inventory aging
                            </Text>
                            <View style={styles.agingChart}>
                                <PdfGraph
                                    data={aging}
                                    fullWidth
                                    height={150}
                                    legend="none"
                                    showValues
                                    subtitle="Inventory value by sales activity"
                                    title="Aging buckets"
                                    variant="horizontal-bar"
                                />
                            </View>
                        </Section>

                        <Section
                            padding="md"
                            spacing="none"
                            variant="card"
                        >
                            <Text
                                color="mutedForeground"
                                noMargin
                                style={styles.sectionTitle}
                                variant="xs"
                            >
                                Recommended actions
                            </Text>
                            <PdfList
                                gap="sm"
                                items={actionItems}
                                variant="numbered"
                            />
                        </Section>

                        <Section spacing="sm">
                            <Text
                                color="mutedForeground"
                                noMargin
                                style={styles.sectionTitle}
                                variant="xs"
                            >
                                Top products
                            </Text>
                            {topProducts.length > 0 ? (
                                <DataTable
                                    columns={[
                                        {
                                            header: "Product",
                                            key: "product",
                                            width: "34%",
                                        },
                                        {
                                            header: "SKU",
                                            key: "sku",
                                            width: "18%",
                                        },
                                        {
                                            align: "right",
                                            header: "Units",
                                            key: "quantity",
                                            width: "12%",
                                        },
                                        {
                                            align: "right",
                                            header: "Revenue",
                                            key: "revenue",
                                            width: "18%",
                                        },
                                        {
                                            align: "right",
                                            header: "Profit",
                                            key: "profit",
                                            width: "18%",
                                        },
                                    ]}
                                    data={topProducts}
                                    size="compact"
                                    stripe
                                    variant="compact"
                                />
                            ) : (
                                <Text color="mutedForeground" variant="sm">
                                    No completed sales in this period.
                                </Text>
                            )}
                        </Section>
                        <View style={styles.footerGap} />
                    </View>
                </Page>
            </Document>
        </PdfcnThemeProvider>
    );
}
